<?php
	// mapping anak perusahaan
	$anak_perusahaan = array(
		array(
			'company' => '4547d242-0ed5-4d09-ac37-420e5e19a703',
			'name' => 'Witon (Wika Beton)',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		array(
			'company' => 'c0b9186f-75d6-4865-b0f3-890d7db8fa2e',
			'name' => 'Wikon',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		array(
			'company' => '514f7570-0c8f-4589-9368-69465c8b5ed2',
			'name' => 'WR (Wika Realty)',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		array(
			'company' => '8d6255cb-1067-4ac9-a9bf-9c086363267',
			'name' => 'WG (Wika Gedung)',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		// ganti
		array(
			'company' => '9c791f07-bf39-4186-a317-7965e547dde7',
			'name' => 'Wijaya Karya',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		array(
			'company' => '73bf37c7-8bde-4678-92d7-1b9882bbd1a4',
			'name' => 'Bitumen',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
		array(
			'company' => 'cc7c5a60-2e2a-424e-852b-562bbf0a239d',
			'name' => 'Serpan',
			'rkap' => 0,
			'terendah' => 0,
			'terkontrak' => 0,
			'sum_terendah_terkontrak' => 0,
			'diperoleh' => 0,
			'nilai_tactic' => 0,
			'ci_nilai' => 0,
			'ci_jumlah' => 0,
			'jumlah_proyek' => 0,
			'jumlah_terendah_terkontrak' => 0,
		),
	);
